# Generated by Django 5.0.6 on 2024-06-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('authors', models.CharField(default=None, max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('position', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=100)),
                ('linkedin', models.URLField(default=None, max_length=100)),
                ('github', models.URLField(default=None, max_length=100)),
                ('pic', models.ImageField(default=None, upload_to='media\\images')),
            ],
        ),
    ]
