# Generated by Django 5.0.6 on 2024-06-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
